import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createApp} from './app.js';
import {createAuthRouter} from '../services/auth.js';
import {createAuthController} from '../controllers/authController.js';
import {createEmailAuthService} from './emailAuth.js';
import {createAccountService} from './accounts.js';
import {authRepository} from './testing/authRepository.js';

test('real HTTP signup/login/recovery flow requires email codes and never touches PostgreSQL',async t=>{
  const {db,tables}=authRepository();let time=new Date('2026-10-04T12:00Z');const codes=[],alerts=[];
  const mail={ensureConfigured(){},async sendCode(data){codes.push(data)},async sendPasswordChanged(data){alerts.push(data)}};
  const service=createAccountService({database:()=>db,now:()=>time});
  const emailAuth=createEmailAuthService({database:()=>db,now:()=>time,mail,credentials:service});
  const router=createAuthRouter({controller:createAuthController({service,emailAuth,secure:true})});
  const server=createApp({authenticationRouter:router}).listen(0,'127.0.0.1');await once(server,'listening');
  t.after(()=>{server.closeAllConnections();server.close()});
  const url='http://127.0.0.1:'+server.address().port;
  const fields={email:'http@example.test',name:'HTTP Test',password:'initialPass123'};
  const request=(path,body,cookie='',headers={})=>fetch(url+'/api/auth/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Requested-With':'energy-web-app',Cookie:cookie,...headers},...(body?{body:JSON.stringify(body)}:{})});
  const cookie=(response,name)=>response.headers.getSetCookie().find(value=>value.startsWith(name+'='))?.split(';')[0];
  const start=await request('register',fields);assert.equal(start.status,202);
  const signup=await start.json();assert.equal(signup.verificationRequired,true);assert.equal(signup.token,undefined);assert.equal(signup.user,undefined);
  assert.equal(tables.session.size,0);assert.equal(cookie(start,'energy_session'),undefined);
  assert.match(start.headers.get('set-cookie'),/HttpOnly/);assert.match(start.headers.get('set-cookie'),/Secure/);assert.match(start.headers.get('set-cookie'),/SameSite=Strict/);
  assert.equal(start.headers.get('cache-control'),'no-store');
  const challengeCookie=cookie(start,'energy_verification');
  const blocked=await fetch(url+'/api/auth/verify-code',{method:'POST',headers:{'Content-Type':'application/json',Cookie:challengeCookie},body:JSON.stringify({code:codes.at(-1).code})});
  assert.equal(blocked.status,403);assert.equal(tables.session.size,0);
  const missing=await request('verify-code',{code:codes.at(-1).code});assert.equal(missing.status,400);
  const verified=await request('verify-code',{code:codes.at(-1).code},challengeCookie);assert.equal(verified.status,200);
  const signedIn=await verified.json();assert.equal(signedIn.user.isEmailVerified,true);assert.ok(signedIn.token);
  const sessionCookie=cookie(verified,'energy_session');
  assert.equal((await (await request('session',null,sessionCookie)).json()).user.email,fields.email);
  assert.equal((await request('verify-code',{code:codes.at(-1).code},challengeCookie)).status,400);
  time=new Date(+time+61000);
  const login=await request('login',{email:fields.email,password:fields.password});assert.equal(login.status,202);assert.equal(cookie(login,'energy_session'),undefined);
  const loginCookie=cookie(login,'energy_verification');assert.equal((await request('verify-code',{code:codes.at(-1).code},loginCookie)).status,200);
  time=new Date(+time+61000);
  const recovery=await request('forgot-password',{email:fields.email});assert.equal(recovery.status,202);
  const recoveryCode=codes.at(-1).code;
  const absent=await request('forgot-password',{email:'missing@example.test'});assert.equal(absent.status,202);
  assert.deepEqual(Object.keys(await absent.json()),Object.keys(await recovery.json()));
  const reset=await request('reset-password',{code:recoveryCode,password:'changedPass123',confirmPassword:'changedPass123'},cookie(recovery,'energy_verification'),{'User-Agent':'HTTP Test Browser','X-Forwarded-For':'9.9.9.9'});
  assert.equal(reset.status,200);assert.equal((await reset.json()).ok,true);assert.equal(tables.session.size,0);
  assert.equal(alerts.length,1);assert.equal(alerts[0].ip,'127.0.0.1');assert.equal(alerts[0].device,'HTTP Test Browser');
  assert.equal((await (await request('session',null,sessionCookie)).json()).user,null);
  assert.equal((await request('reset-password',{token:signedIn.token,code:recoveryCode,password:'newPass123',confirmPassword:'newPass123'})).status,400);
});
