export const COLORS={solar:'#e9a51a',wind:'#168477',hydro:'#356bd8',other:'#8768c9',nuclear:'#69736f',ink:'#14201c'};
export const SEASONS={winter:{name:'Зима',sunrise:7.4,sunset:17,pv:.42,wind:1.15,hydro:.35,demand:1.22},spring:{name:'Пролет',sunrise:6.2,sunset:19,pv:.78,wind:1,hydro:.55,demand:.95},summer:{name:'Лято',sunrise:5.4,sunset:20.2,pv:.84,wind:.7,hydro:.28,demand:1.12},autumn:{name:'Есен',sunrise:6.8,sunset:18.3,pv:.66,wind:.95,hydro:.22,demand:.98}};
export const CAPACITY={solar:3612,wind:707,hydro:2375,other:64};
export const TYPES={solar:{name:'Фотоволтаици',short:'Слънце',color:COLORS.solar},wind:{name:'Вятърна енергия',short:'Вятър',color:COLORS.wind},hydro:{name:'Водноелектрическа',short:'Вода',color:COLORS.hydro}};
export const SITES=[
{id:'pazardzhik',name:'Пазарджик',type:'solar',lon:24.33,lat:42.19,cap:304,to:['plovdiv','sofia'],place:'общ. Пазарджик',note:'Най-голямата концентрация на фотоволтаици в страната по общини.'},
{id:'sliven',name:'Сливен',type:'solar',lon:26.32,lat:42.68,cap:295.5,to:['burgas','starazagora'],place:'общ. Сливен',note:'Втората по мощност община за слънчева енергия.'},
{id:'galabovo',name:'Гълъбово',type:'solar',lon:25.87,lat:42.15,cap:204.5,to:['starazagora','plovdiv'],place:'общ. Гълъбово',note:'В района на комплекса Марица-изток.'},
{id:'kaloyanovo',name:'Калояново',type:'solar',lon:24.93,lat:42.4,cap:201.5,to:['plovdiv'],place:'общ. Калояново',note:'Парковете захранват предимно пловдивския промишлен район.'},
{id:'kavarna',name:'Каварна',type:'wind',lon:28.34,lat:43.43,cap:398.9,to:['varna','devnya'],place:'общ. Каварна',note:'Най-големият вятърен район по Добруджанското крайбрежие.',factor:1.12},
{id:'kazanlak',name:'Казанлък',type:'wind',lon:25.4,lat:42.62,cap:72.5,to:['starazagora','burgas'],place:'общ. Казанлък',note:'Вятърни паркове в подножието на Стара планина.',factor:.9},
{id:'suvorovo',name:'Суворово',type:'wind',lon:27.4,lat:43.33,cap:60,to:['varna','devnya'],place:'общ. Суворово',note:'Вятърни паркове във Варненско.'},
{id:'belovo',name:'Белово',type:'hydro',lon:24.02,lat:42.2,cap:736.2,to:['sofia','plovdiv'],place:'общ. Белово',note:'Каскадата Белмекен–Сестримо–Чаира работи за пикови часове.'},
{id:'krichim',name:'Кричим',type:'hydro',lon:24.47,lat:42.03,cap:261,to:['plovdiv'],place:'общ. Кричим',note:'Водноелектрически централи по Въча.'},
{id:'devin',name:'Девин',type:'hydro',lon:24.4,lat:41.74,cap:238.5,to:['plovdiv'],place:'общ. Девин',note:'Родопски ВЕЦ, захранващи Тракийската низина.'},
{id:'peshtera',name:'Пещера',type:'hydro',lon:24.3,lat:42.03,cap:136.6,to:['sofia','plovdiv'],place:'общ. Пещера',note:'Част от родопския хидро клъстер.'}];
// Town coordinates from OpenStreetMap; see ../frontend/src/data/MAP-SOURCES.md.
export const CITIES=[{"id":"sofia","name":"София","lon":23.32167,"lat":42.697839,"share":19,"who":"услуги, транспорт и домакинства","label":"right"},{"id":"plovdiv","name":"Пловдив","lon":24.748809,"lat":42.159272,"share":8,"who":"индустрия и домакинства","label":"right"},{"id":"varna","name":"Варна","lon":27.910543,"lat":43.204665,"share":6.5,"who":"пристанище, услуги и домакинства","label":"right"},{"id":"burgas","name":"Бургас","lon":27.462636,"lat":42.504793,"share":6,"who":"рафинерия, нефтохимия и пристанище","label":"left"},{"id":"ruse","name":"Русе","lon":25.965655,"lat":43.835571,"share":3,"who":"индустрия и речно пристанище","label":"right"},{"id":"starazagora","name":"Стара Загора","lon":25.634464,"lat":42.425777,"share":4.5,"who":"индустрия и домакинства","label":"right"},{"id":"pleven","name":"Плевен","lon":24.606084,"lat":43.398835,"share":2.5,"who":"услуги и домакинства","label":"left"},{"id":"devnya","name":"Девня","lon":27.5694,"lat":43.2222,"share":3,"who":"химия и циментова промишленост","label":"left"}];
export const NUCLEAR={id:'kozloduy',name:'АЕЦ Козлодуй',lon:23.77,lat:43.75,cap:2000};
export const fmt=n=>Math.round(n).toLocaleString('bg-BG');
export const clock=h=>`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.round((h%1)*60)%60).padStart(2,'0')}`;
export function simulate(state){const s=SEASONS[state.season],h=state.hour,g=(x,m,w)=>Math.exp(-Math.pow((x-m)/w,2)/2);const solarF=h>s.sunrise&&h<s.sunset?s.pv*Math.pow(Math.sin(Math.PI*(h-s.sunrise)/(s.sunset-s.sunrise)),1.4)*(1-.75*state.cloud/100):0;const windF=Math.max(0,Math.min(.85,state.wind/100*.6*s.wind*(1+.18*Math.cos(2*Math.PI*(h-2)/24))));const hydroF=Math.min(.85,s.hydro+.14*(g(h,8,1.6)+1.2*g(h,19,2)));const mw={solar:CAPACITY.solar*solarF,wind:CAPACITY.wind*windF,hydro:CAPACITY.hydro*hydroF,other:CAPACITY.other*.55};const res=Object.values(mw).reduce((a,b)=>a+b,0),profile=(.8+.12*g(h,8.5,2.2)+.07*g(h,13,2.5)+.22*g(h,19.5,2.3))/.9,demand=3785*s.demand*profile,day=g(h,13,4.5),eve=.6*g(h,8,2)+g(h,20,2.5);const raw=[['Индустрия',.4*(.88+.2*day),'#14201c'],['Домакинства',.3*(.7+.55*eve),'#53615b'],['Услуги и търговия',.22*(.55+.6*day),'#8b9791'],['Транспорт и селско ст.',.08*(.85+.2*day),'#c0c8c3']],sum=raw.reduce((a,x)=>a+x[1],0),sectors=raw.map(x=>({label:x[0],mw:demand*x[1]/sum,pct:x[1]/sum,color:x[2]}));const cityDemand={},cityRes={},cityFrom={};CITIES.forEach(c=>{cityDemand[c.id]=demand*c.share/52.5;cityRes[c.id]=0;cityFrom[c.id]=[]});const siteOut={};SITES.forEach(site=>{const totalCap=SITES.filter(x=>x.type===site.type).reduce((a,x)=>a+x.cap,0),output=mw[site.type]*site.cap/totalCap*(site.factor||1);siteOut[site.id]=output;site.to.forEach(id=>{const amount=output/site.to.length;cityRes[id]+=amount;cityFrom[id].push({site,mw:amount})})});return{mw,res,demand,coverage:res/demand*100,sectors,siteOut,cityDemand,cityRes,cityFrom}}
